### PR TITLE
Removed componentWillReceiveProps

### PR DESCRIPTION
**Pull request by Martinnord**
Removed `componentWillReceiveProps` and replaced it with `componentDidUpdate`.

### CODE REVIEW

**Comment by Martinnord** [comment]
Noticed the test is failing, but I guess it's because of the URL that points to `http://localhost:8089/handler` in the `subscribe.test.js` file?

**Comment by lahsivjar** [comment]
Hi Martin,

> Noticed the test is failing, but I guess it's because of the URL that points to http://localhost:8089/handler in the subscribe.test.js file?

The subscribe test is an end-to-end test using a running server. The url `localhost:8089` is correct and it points to the docker container running at that port. I use [this](https://github.com/lahsivjar/stomp-test-docker-image) docker image for the server part.

The reason why test is failing is because `componentDidUpdate` is invoked *after* component updates however `react-stomp` returns `false` for every `shouldComponentUpdate` call thereby disabling any re-render of the component (https://github.com/lahsivjar/react-stomp/blob/d69cd26c1af2b05b6643cc8dfb66d3f8fdec49ea/src/client.jsx#L119-L121)

The reason why this is done is because as per the previous logic `react-stomp` doesn't need to update in any case. Let's consider all types of props handled by this component:

1. Props passed to the underlying websocket: Changes to props of this category will result in recreating the websocket client
2. Props used to manage subscriptions: Changes to such props will mean updating the subscriptions

Neither cases need to update. So the react lifecycle method shouldComponentUpdate can return false for all cases.

We need to reconsider the lifecycle of `react-stomp` for this PR.

**Comment by Martinnord** [comment]
Hmm. You are probably right. We are using your library in our project and I just switched out the lifecycle methods and everything worked as before. Minus the warning of course. I was probably just naive enough to submit the PR.

**Comment by lahsivjar** [comment]
@Martinnord No worries. Will you be able to work on this?

**Pull request closed without merging**
